<?php
/*
Plugin Name: Blog Summary
Plugin URI: https://wordpress.org/extend/plugins/2013-summary/ TODO Änderung derr Adresse
Description: Get a brief summary of your blog. How many posts, how many pages, who has commented -
             all data on one page and with the possibility to create a post.
Version: 0.1.1
Author: Addapted to 2013 by Elias Kirchgässner from Tomasz Topa (http://tomasz.topa.pl)
Author URI: http://www.lioman.de
License: GPL v2 - http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

	Copyright 2013  Elias Kirchgässner (email: blog [at] lioman.de)

     Original code from Tomasz Topa  (email : wpsummary [at] topa.pl)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as
    published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

Min WP Version: 3.5
Max WP Version: 3.8
*/

add_action('admin_menu', 'y2013summary_menu_add');

$y2013summary_translations = array('en');
$y2013summary_lang = substr(WPLANG, 0, 2);
if (!in_array($y2013summary_lang, $y2013summary_translations)) {
    $y2013summary_lang = 'en';
}

/* Translation */

$y2013summary_trans = array();
$y2013summary_trans[1] = array(
    'en' => '2013 Summary - whole year of blogging summarized'
);
$y2013summary_trans[2] = array(
    'en' => 'This plugin <strong>generates a brief summary of your blog</strong> for one year.'
);
$y2013summary_trans[3] = array(
    'en' => 'See how many posts you wrote durig the ending year,  which were the most popular, who was the most active commenter etc.'
);
$y2013summary_trans[4] = array(
    'en' => 'And then <strong>share the stats with your readers</strong> - copy the data to a new draft with a single click.'
);
$y2013summary_trans[5] = array(
    'en' => 'Summary of 2013'
);
$y2013summary_trans[6] = array(
    'en' => '<strong>A draft of the new post has been created</strong>. You can now '
);
$y2013summary_trans[7] = array(
    'en' => 'edit it'
);
$y2013summary_trans[8] = array(
    'en' => 'and then publish.'
);
$y2013summary_trans[9] = array(
    'en' => 'Regenerate summary'
);
$y2013summary_trans[10] = array(
    'en' => 'Generate summary'
);
$y2013summary_trans[11] = array(
    'en' => 'Questions? Mail me: blog@lioman.de or <a href="http://twitter.com/lioman" rel="nofollow">@lioman</a>. You can also check out my blog at <a href="http://www.lioman.de">www.lioman.de</a>'
);
$y2013summary_trans[12] = array(
    'en' => 'comments'
);
$y2013summary_trans[13] = array(
    'en' => 'posts'
);
$y2013summary_trans[14] = array(
    'en' => 'In 2013 you wrote <strong>%s</strong> posts and added <strong>%s pages</strong> to this blog, with <strong>%s attachments</strong> in total.'
);
$y2013summary_trans[15] = array(
    'en' => 'The number of posts in each month'
);
$y2013summary_trans[16] = array(
    'en' => 'The number of posts in each day of week'
);
$y2013summary_trans[17] = array(
    'en' => 'At what hours you publish new posts'
);
$y2013summary_trans[18] = array(
    'en' => 'In 2013 your posts were commented <strong>%s</strong> times, from which <strong>%s</strong> comments (%s percent) were written by registered users/authors.'
);
$y2013summary_trans[19] = array(
    'en' => 'TOP 10 commenters in 2013'
);
$y2013summary_trans[20] = array(
    'en' => 'TOP 10 most commented posts in 2013'
);
$y2013summary_trans[21] = array(
    'en' => 'The number of comments in each month'
);
$y2013summary_trans[22] = array(
    'en' => 'On what days people comment'
);
$y2013summary_trans[23] = array(
    'en' => 'At what hours people comment'
);
$y2013summary_trans[24] = array(
    'en' => '<strong>This blog has many authors.</strong> Here is the number of posts each one wrote:'
);
$y2013summary_trans[25] = array(
    'en' => 'And the number of comments each one wrote:'
);
$y2013summary_trans[26] = array(
    'en' => 'Summary generated by <a href="https://wordpress.org/extend/plugins/2013-summary/">2013 Summary plugin</a>'
);
$y2013summary_trans[27] = array(
    'en' => 'Create a new blog post with this summary'
);
$y2013summary_trans[28] = array(
    'en' => '2013 Summary'
);
$y2013summary_trans[29] = array(
    'en' => array('your', 'you', '<p>&nbsp;</p>')
);
$y2013summary_trans[30] = array(
    'en' => array('the', 'I', '')
);

function y2013summary_menu_add()
{
    add_submenu_page('index.php', '2013 Summary', '2013 Summary', 'read', 'y2013summary', 'y2013summary');
}

function y2013summary()
{
    global $y2013summary_trans, $y2013summary_lang, $y2013summary_translations;
    if (!current_user_can('read')) {
        wp_die(__('You do not have sufficient permissions to access this page.'));
    }


    echo '<div class="wrap">

	<style type="text/css">
	.y2013summaryList{font-size:11px;margin-left:3em;list-style:disc;}
	#y2013summaryDonate{width:292px;height:420;position:absolute;top:5px;right:5px;float:right;text-align:center;}
	.y2013summaryTable{margin: 0 0 0 10px;}
	.y2013summaryTable td{font-size:11px;line-height:2em;padding:0.25em;overflow:hidden;}
	.y2013summaryCol1{float:left;width:300px;overflow:hidden;}
	.y2013summaryCol2{float:left;width:260px;overflow:hidden;}
	.y2013summaryClear{clear:both;}
	</style>

	<h2>' . $y2013summary_trans[1][$y2013summary_lang] . '</h2>
	<div id="y2013summaryDonate">
	<iframe src="http://tools.flattr.net/widgets/thing.html?thing=1093328" width="292" height="420"></iframe>

	</div>
	<p>' . $y2013summary_trans[2][$y2013summary_lang] . '</p>
	<p>' . $y2013summary_trans[3][$y2013summary_lang] . '</p>
	<p>' . $y2013summary_trans[4][$y2013summary_lang] . '</p>



	';


    if ($_POST['y2013summary_generate'] == true) {
        y2013summary_generate();

    } elseif ($_POST['y2013summary_draft'] == true) {

        $my_post = array(
            'post_title' => $y2013summary_trans[5][$y2013summary_lang],
            'post_content' => base64_decode($_POST['y2013summary_draftcontent']),
            'post_status' => 'draft',
            'post_author' => $user_ID,
        );

// Insert the post into the database
        $postid = wp_insert_post($my_post);

        echo '<p>&nbsp;</p><div class="updated"><p>' . $y2013summary_trans[6][$y2013summary_lang] . ' <a href="' . get_bloginfo(
                'wpurl'
            ) . '/wp-admin/post.php?post=' . $postid . '&action=edit">' . $y2013summary_trans[7][$y2013summary_lang] . '</a> ' . $y2013summary_trans[8][$y2013summary_lang] . '</p></div>';
        echo '<p>&nbsp;</p><p>&nbsp;</p><form name="y2013summary_generate" method="post" action="">
	<input type="submit" name="generateStats" class="button-primary" value="' . $y2013summary_trans[9][$y2013summary_lang] . '" />
	<input type="hidden" name="y2013summary_generate" value="TRUE" />
	</form>';

    } else {
        echo '<form name="y2013summary_generate" method="post" action="">
	<input type="submit" name="generateStats" class="button-primary" value="' . $y2013summary_trans[10][$y2013summary_lang] . '" />
	<input type="hidden" name="y2013summary_generate" value="TRUE" />
	</form>';

    }

    echo '<p>&nbsp;</p><p>&nbsp;</p><hr><p><small>' . $y2013summary_trans[11][$y2013summary_lang] . '</small></p>';
    echo '</div>';
}

function y2013summary_generate()
{
    global $wpdb, $y2013summary_trans, $y2013summary_lang, $y2013summary_translations;


    $y2013summary_noposts = $wpdb->get_row(
        "SELECT count($wpdb->posts.ID) as howmany FROM $wpdb->posts WHERE year(post_date)=2013 and post_type='post' and post_status='publish'"
    );

    $y2013summary_nopages = $wpdb->get_row(
        "SELECT count($wpdb->posts.ID) as howmany FROM $wpdb->posts WHERE year(post_date)=2013 and post_type='page' and post_status='publish'"
    );

    $y2013summary_noattach = $wpdb->get_row(
        "SELECT count($wpdb->posts.ID) as howmany FROM $wpdb->posts WHERE year(post_date)=2013 and $wpdb->posts.post_type='attachment'"
    );

    $y2013summary_noauthors = $wpdb->get_row("SELECT count($wpdb->users.ID) as howmany FROM $wpdb->users");

    $y2013summary_nocomm = $wpdb->get_row(
        "SELECT count($wpdb->comments.comment_ID) as howmany FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and $wpdb->comments.comment_type!='trackback' and $wpdb->comments.comment_approved=1"
    );

    $y2013summary_commbyauthors = $wpdb->get_results(
        "SELECT count($wpdb->comments.comment_ID) as howmany, $wpdb->comments.user_id FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and $wpdb->comments.comment_type!='trackback' and $wpdb->comments.comment_approved=1 and $wpdb->comments.user_id>0 group by $wpdb->comments.user_id"
    );

    $y2013summary_nocommr = $wpdb->get_row(
        "SELECT count($wpdb->comments.comment_ID) as howmany FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and comment_type!='trackback' and $wpdb->comments.user_id>0 and $wpdb->comments.comment_approved=1"
    );

    $y2013summary_months = $wpdb->get_results(
        "SELECT count($wpdb->posts.ID) as howmany, month($wpdb->posts.post_date) as postmonth FROM $wpdb->posts WHERE year(post_date)=2013 and $wpdb->posts.post_type='post' group by postmonth order by postmonth asc"
    );

    $y2013summary_hours = $wpdb->get_results(
        "SELECT count($wpdb->posts.ID) as howmany, hour($wpdb->posts.post_date) as posthour FROM $wpdb->posts WHERE year(post_date)=2013 and $wpdb->posts.post_type='post' group by posthour order by posthour asc"
    );


    $y2013summary_days = $wpdb->get_results(
        "SELECT count($wpdb->posts.ID) as howmany, dayname($wpdb->posts.post_date) as postday, dayofweek($wpdb->posts.post_date) as postday2 FROM $wpdb->posts WHERE year(post_date)=2013 and $wpdb->posts.post_type='post' group by postday order by postday2 asc"
    );


    $y2013summary_postsbyauthors = $wpdb->get_results(
        "SELECT count($wpdb->posts.ID) as howmany, $wpdb->posts.post_author FROM $wpdb->posts WHERE year(post_date)=2013 and $wpdb->posts.post_type='post' group by $wpdb->posts.post_author order by howmany desc"
    );

    $y2013summary_topcom = $wpdb->get_results(
        "SELECT $wpdb->posts.comment_count, $wpdb->posts.post_title, $wpdb->posts.ID FROM $wpdb->posts WHERE year($wpdb->posts.post_date)=2013 and $wpdb->posts.post_type='post' order by comment_count desc limit 10"
    );

    $y2013summary_commenters = $wpdb->get_results(
        "SELECT count($wpdb->comments.comment_ID) as howmany,$wpdb->comments.comment_author FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and comment_type!='trackback' and $wpdb->comments.comment_approved=1 and user_id=0 group by $wpdb->comments.comment_author order by howmany desc limit 10"
    );

    $y2013summary_commentsday = $wpdb->get_results(
        "SELECT count($wpdb->comments.comment_ID) as howmany, dayname($wpdb->comments.comment_date) as commentday, dayofweek($wpdb->comments.comment_date) as commentday2 FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and comment_type!='trackback' and $wpdb->comments.comment_approved=1 group by commentday order by commentday2 asc"
    );

    $y2013summary_commentmonths = $wpdb->get_results(
        "SELECT count($wpdb->comments.comment_ID) as howmany, month($wpdb->comments.comment_date) as commentmonth FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and comment_type!='trackback' and $wpdb->comments.comment_approved=1 group by commentmonth order by commentmonth asc"
    );


    $y2013summary_commenthours = $wpdb->get_results(
        "SELECT count($wpdb->comments.comment_ID) as howmany, hour($wpdb->comments.comment_date) as commenthour FROM $wpdb->comments WHERE year($wpdb->comments.comment_date)=2013 and comment_type!='trackback' and $wpdb->comments.comment_approved=1 group by commenthour order by commenthour asc"
    );

    foreach ($y2013summary_commenters as $y2013summary_commenter) {
        $y2013summary_commentdata .= '<li>' . $y2013summary_commenter->comment_author . ': <strong>' . $y2013summary_commenter->howmany . '</strong> ' . $y2013summary_trans[12][$y2013summary_lang] . '</li>';
    }

    foreach ($y2013summary_months as $y2013summary_month) {
        $y2013summary_monthdata .= '<tr><td style="width:110px;text-align:right;font-weight:bold;">' . __(
                date("F", mktime(0, 0, 0, $y2013summary_month->postmonth, 1, 2013))
            ) . ':</td><td><div class="y2013summaryChartBar" style="width:' . round(
                $y2013summary_month->howmany / $y2013summary_noposts->howmany * 70
            ) . 'px"></div> &nbsp; ' . $y2013summary_month->howmany . ' (' . round(
                $y2013summary_month->howmany / $y2013summary_noposts->howmany * 100,
                2
            ) . '%)</td></tr>';
    }

    foreach ($y2013summary_commentmonths as $y2013summary_commentmonth) {
        $y2013summary_commentmonthdata .= '<tr><td style="width:110px;text-align:right;font-weight:bold;">' . __(
                date("F", mktime(0, 0, 0, $y2013summary_commentmonth->commentmonth, 1, 2013))
            ) . ':</td><td><div class="y2013summaryChartBar" style="width:' . round(
                $y2013summary_commentmonth->howmany / $y2013summary_nocomm->howmany * 70
            ) . 'px"></div> &nbsp; ' . $y2013summary_commentmonth->howmany . ' (' . round(
                $y2013summary_commentmonth->howmany / $y2013summary_nocomm->howmany * 100,
                2
            ) . '%)</td></tr>';
    }

    foreach ($y2013summary_hours as $y2013summary_hour) {
        $y2013summary_hourdata .= '<tr><td style="width:50px;text-align:right;font-weight:bold;">' . $y2013summary_hour->posthour . ':</td><td><div class="y2013summaryChartBar" style="width:' . round(
                $y2013summary_hour->howmany / $y2013summary_noposts->howmany * 70
            ) . 'px"></div> &nbsp; ' . $y2013summary_hour->howmany . ' (' . round(
                $y2013summary_hour->howmany / $y2013summary_noposts->howmany * 100,
                2
            ) . '%)</td></tr>';
    }

    foreach ($y2013summary_commenthours as $y2013summary_commenthour) {
        $y2013summary_commenthourdata .= '<tr><td style="width:50px;text-align:right;font-weight:bold;">' . $y2013summary_commenthour->commenthour . ':</td><td><div class="y2013summaryChartBar" style="width:' . round(
                $y2013summary_commenthour->howmany / $y2013summary_nocomm->howmany * 70
            ) . 'px"></div> &nbsp; ' . $y2013summary_commenthour->howmany . ' (' . round(
                $y2013summary_commenthour->howmany / $y2013summary_nocomm->howmany * 100,
                2
            ) . '%)</td></tr>';
    }

    foreach ($y2013summary_days as $y2013summary_day) {

        $y2013summary_daydata .= '<tr><td style="width:110px;text-align:right;font-weight:bold;">' . __(
                $y2013summary_day->postday
            ) . ':</td><td><div class="y2013summaryChartBar" style="width:' . round(
                $y2013summary_day->howmany / $y2013summary_noposts->howmany * 70
            ) . 'px"></div> &nbsp; ' . $y2013summary_day->howmany . ' (' . round(
                $y2013summary_day->howmany / $y2013summary_noposts->howmany * 100,
                2
            ) . '%)</td></tr>';

    }

    foreach ($y2013summary_commentsday as $y2013summary_commentday) {

        $y2013summary_commentdaydata .= '<tr><td style="width:110px;text-align:right;font-weight:bold;">' . __(
                $y2013summary_commentday->commentday
            ) . ':</td><td><div class="y2013summaryChartBar" style="width:' . round(
                $y2013summary_commentday->howmany / $y2013summary_nocomm->howmany * 70
            ) . 'px"></div> &nbsp; ' . $y2013summary_commentday->howmany . ' (' . round(
                $y2013summary_commentday->howmany / $y2013summary_nocomm->howmany * 100,
                2
            ) . '%)</td></tr>';

    }

    foreach ($y2013summary_topcom as $y2013summary_post) {
        $y2013summary_postdata .= '<li><a href="' . get_permalink(
                $y2013summary_post->ID
            ) . '">' . $y2013summary_post->post_title . '</a>: <strong>' . $y2013summary_post->comment_count . '</strong> ' . $y2013summary_trans[12][$y2013summary_lang] . '</li>';
    }


    foreach ($y2013summary_postsbyauthors as $y2013summary_author) {
        $y2013summary_authorprofile = get_userdata($y2013summary_author->post_author);
        $y2013summary_authordata .= '<li>' . $y2013summary_authorprofile->display_name . ': <strong>' . $y2013summary_author->howmany . '</strong> ' . $y2013summary_trans[13][$y2013summary_lang] . '</li>';
    }

    foreach ($y2013summary_commbyauthors as $y2013summary_commauthor) {
        $y2013summary_authorprofile2 = get_userdata($y2013summary_commauthor->user_id);
        $y2013summary_commauthordata .= '<li>' . $y2013summary_authorprofile2->display_name . ': <strong>' . $y2013summary_commauthor->howmany . '</strong> ' . $y2013summary_trans[12][$y2013summary_lang] . '</li>';
    }


    $y2013summary_text .= '
	<style type="text/css">.y2013summaryChartBar{height:15px;background:#1A87D5;display:inline-block;}</style>
	<p>' . sprintf(
            $y2013summary_trans[14][$y2013summary_lang],
            $y2013summary_noposts->howmany,
            $y2013summary_nopages->howmany,
            $y2013summary_noattach->howmany
        ) . '</p>
	<p>&nbsp;</p>
	<div class="y2013summaryCol1">
	<p><strong>' . $y2013summary_trans[15][$y2013summary_lang] . ':</strong></p>
	<table class="y2013summaryTable">' . $y2013summary_monthdata . '</table>

	<p>&nbsp;</p>

	<p><strong>' . $y2013summary_trans[16][$y2013summary_lang] . ':</strong></p>
	<table class="y2013summaryTable">' . $y2013summary_daydata . '</table>

	</div>
	<div class="y2013summaryCol2">
	<p><strong>' . $y2013summary_trans[17][$y2013summary_lang] . ':</strong></p>
	<table class="y2013summaryTable">' . $y2013summary_hourdata . '</table>
	</div>
	<div class="y2013summaryClear"></div>
	<p>&nbsp;</p>
	<p>' . sprintf(
            $y2013summary_trans[18][$y2013summary_lang],
            $y2013summary_nocomm->howmany,
            $y2013summary_nocommr->howmany,
            round($y2013summary_nocommr->howmany / $y2013summary_nocomm->howmany * 100, 2)
        ) . '</p>
	<p>&nbsp;</p>
	<p><strong>' . $y2013summary_trans[19][$y2013summary_lang] . ':</strong></p>
	<ul class="y2013summaryList">' . $y2013summary_commentdata . '</ul>
	<p>&nbsp;</p>
	<p><strong>' . $y2013summary_trans[20][$y2013summary_lang] . ':</strong></p>
	<ul class="y2013summaryList">' . $y2013summary_postdata . '</ul>
	<p>&nbsp;</p>
	<div class="y2013summaryCol1">
	<p><strong>' . $y2013summary_trans[21][$y2013summary_lang] . ':</strong></p>
	<table class="y2013summaryTable">' . $y2013summary_commentmonthdata . '</table>
	<p>&nbsp;</p>
	<p><strong>' . $y2013summary_trans[22][$y2013summary_lang] . ':</strong></p>
	<table class="y2013summaryTable">' . $y2013summary_commentdaydata . '</table>
	</div>
	<div class="y2013summaryCol2">
	<p><strong>' . $y2013summary_trans[23][$y2013summary_lang] . ':</strong></p>
	<table class="y2013summaryTable">' . $y2013summary_commenthourdata . '</table>
	</div>
	<div class="y2013summaryClear"></div>
	';

    if ($y2013summary_noauthors->howmany > 1) {
        $y2013summary_text .= '<p>' . $y2013summary_trans[24][$y2013summary_lang] . '</p>
		<ul class="y2013summaryList">' . $y2013summary_authordata . '</ul>
		<p>&nbsp;</p>
		<p>' . $y2013summary_trans[25][$y2013summary_lang] . '</p>
		<ul class="y2013summaryList">' . $y2013summary_commauthordata . '</ul>
		<p>&nbsp;</p>
		';

    }


    $y2013summary_draft = base64_encode(
        str_replace(
            $y2013summary_trans[29][$y2013summary_lang],
            $y2013summary_trans[30][$y2013summary_lang],
            $y2013summary_text
        ) . '<p>' . $y2013summary_trans[26][$y2013summary_lang] . '</p>'
    );

    echo '<p>&nbsp;</p><form name="y2013summary_draft" method="post" action=""><input type="submit" name="generateDraft" class="button-primary" value="' . $y2013summary_trans[27][$y2013summary_lang] . '" />
  <input type="hidden" name="y2013summary_draft" value="TRUE" />
  <input type="hidden" name="y2013summary_draftcontent" value="' . $y2013summary_draft . '" />
  </form>&nbsp;
	<div id="poststuff"><div class="postbox"><h3 class="hndle"><span>' . $y2013summary_trans[28][$y2013summary_lang] . '</span></h3><div class="inside"><p>&nbsp;</p>';
    echo $y2013summary_text;

    echo '</div></div></div>';

    echo '<form name="y2013summary_draft" method="post" action="">
  <input type="submit" name="generateDraft" class="button-primary" value="' . $y2013summary_trans[27][$y2013summary_lang] . '" />
  <input type="hidden" name="y2013summary_draft" value="TRUE" />
  <input type="hidden" name="y2013summary_draftcontent" value="' . $y2013summary_draft . '" />
  </form>
  <p>&nbsp;</p>';

}

?>
